import React from 'react';

import { PubPageData, DefinitelyHas } from 'types';

import { usePageContext } from 'utils/hooks';
import { PubThemePicker, PopoverButton, DownloadChooser } from 'components';
import SmallHeaderButton from '../../PubHeader/SmallHeaderButton';

require('./spubSettings.scss');

type Props = {
	pubData: DefinitelyHas<PubPageData, 'submission'>;
	onUpdatePub: (pub: Partial<PubPageData>) => unknown;
};

const SpubSettings = (props: Props) => {
	const { communityData } = usePageContext();
	const renderHeaderAndBackgroundSetting = () => {
		return (
			<div className="submission-tab-prompt">
				<div className="submission-tab-prompt-text">
					<h2>Header Background & Theme</h2>
					<p>
						You can pick a background image and a custom visual theme for the header of
						your submission pub.
					</p>
					<p>
						Once you've made your changes, use the Preview tab to see the updated header
						of your submission pub.
					</p>
				</div>
				<div>
					&nbsp;
					<PopoverButton
						component={PubThemePicker}
						className="pub-header-popover"
						updatePubData={props.onUpdatePub}
						pubData={props.pubData}
						communityData={communityData}
						aria-label="Pub header theme options"
					>
						<SmallHeaderButton
							label="EDIT PUB THEME"
							labelPosition="right"
							icon="clean"
							className="label"
						/>
					</PopoverButton>
				</div>
			</div>
		);
	};

	const renderDefaultDownloadFile = () => {
		return (
			<div className="submission-tab-prompt">
				<div className="submission-tab-prompt-text">
					<h2>Default Download File</h2>
					<p className="submission-tab-prompt-text">
						Readers of your submission pub can choose to download it as a file,
						available in different formats automatically generated by PubPub.
						<br />
						<br />
						You can upload a file, like a PDF with custom styling, to associate with
						your pub. It will be provided to readers as the pub's default download, but
						they'll still be able to use the automatic export tools.
					</p>
				</div>

				<div>
					<DownloadChooser
						pubData={props.pubData}
						communityId={communityData.id}
						onSetDownloads={props.onUpdatePub}
						text="UPLOAD YOUR FILE"
						isMinimal
						isSmall
					/>
				</div>
			</div>
		);
	};

	return (
		<div className="submission-tab-tabs">
			{renderHeaderAndBackgroundSetting()}
			{renderDefaultDownloadFile()}
		</div>
	);
};

export default SpubSettings;
