process.env.DATABASE_URL = '<YOUR-POSTGRES-URI>';
process.env.POSTMARK_API_KEY = '<API-KEY>';
process.env.AWS_ACCESS_KEY_ID = '<ACCESS-KEY>';
process.env.AWS_SECRET_ACCESS_KEY = '<SECRET-KEY>';
process.env.STREAM_API_KEY = '<STREAM-API-KEY>';
process.env.STREAM_API_KEY_SECRET = '<STREAM-API-KEY-SECRET>';
