footnotes:
	node -r esm --max-old-space-size=12000 migrateFootnotes.js
	
citations:
	node -r esm --max-old-space-size=12000 migrateCitations.js
	
checkpoints:
	node -r esm --max-old-space-size=12000 backfillCheckpoints.js
